[package]
name = "imsearch"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.98", features = ["backtrace"] }
directories = "6.0.0"
fdlimit = "0.3.0"
num_cpus = "1.16.0"
once_cell = "1.21.3"
rayon = "1.10.0"
regex = "1.11.1"
serde_json = "1.0.140"
structopt = "0.3.26"
walkdir = "2.5.0"
itertools = "0.14.0"
env_logger = "0.11.8"
log = "0.4.27"
dashmap = "6.1.0"
crossbeam-utils = "0.8.21"
blake3 = "1.8.2"
rouille = "3.6.2"
tempfile = "3.19.1"
ndarray = "0.16.1"
ndarray-npy = "0.9.1"

[dependencies.faiss-sys]
version = "0.6.3-alpha.0"
git = "https://github.com/Aloxaf/faiss-rs"
branch = "feat/c_api_binary_ivf"
features = ["static"]

[dependencies.opencv]
version = "0.94.4"
default-features = false
features = [
    "clang-runtime",
    "highgui",
    "features2d",
    "flann",
    "imgcodecs",
    "imgproc",
]

[dependencies.rocksdb]
version = "0.21.0"
default-features = false
features = ["lz4", "zstd", "multi-threaded-cf"]

[build-dependencies]
cc = "1.2.19"
dunce = "1.0.5"
glob = "0.3.2"
once_cell = "1.21.3"
pkg-config = "0.3.32"
semver = "1.0.26"
shlex = "1.3.0"
vcpkg = "0.2.15"
